# Generated by Django 5.1.6 on 2025-02-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="status",
            field=models.CharField(
                choices=[
                    ("TO_DO", "To Do"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                ],
                default="TO_DO",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
